version: '3.8'

services:
  litespeed:
    image: litespeedtech/openlitespeed:latest
    container_name: litespeed
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
      - "${OLS_ADMIN_PORT}:7080"
    volumes:
      - ./wordpress:/var/www/vhosts/localhost/html # WordPress
      - ./litespeed/conf:/usr/local/lsws/conf # OLS
      - ./php/php.ini:/usr/local/lsws/lsphp74/etc/php/php.ini # PHP
    environment:
      - TZ=${TZ}
    depends_on:
      - database
      - redis
    networks:
      - network

  database:
    image: mariadb:10.6
    container_name: database
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - database_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${DB_NAME}'
      MYSQL_USER: '${DB_USER}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    restart: unless-stopped
    networks:
      - network

  adminer:
    image: adminer
    container_name: adminer
    restart: unless-stopped
    ports:
      - "${ADMINER_PORT}:8080"
    depends_on:
      - database
    networks:
      - network

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    networks:
      - network

  wpcli:
    image: wordpress:cli
    container_name: wpcli
    volumes:
      - ./wordpress:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/conf.d/custom-memory.ini
    depends_on:
      - database
      - redis
    environment:
      - WORDPRESS_DB_HOST=database
      - WORDPRESS_DB_USER=${DB_USER}
      - WORDPRESS_DB_PASSWORD=${DB_PASSWORD}
      - WORDPRESS_DB_NAME=${DB_NAME}
      
      - WP_HOME=${WP_HOME}
      - WP_ADMIN_USER=${WP_ADMIN_USER}
      - WP_ADMIN_PASSWORD=${WP_ADMIN_PASSWORD}
      - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
      - WP_CACHE_KEY_SALT=${WP_CACHE_KEY_SALT}
      - PHP_INI_MEMORY_LIMIT=256M
    networks:
      - network

networks:
  network:
    driver: bridge

volumes:
  database_data:
